spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update  # or create, create-drop, validate based on your needs
    show-sql: true  # Set to true to log SQL queries
